name: Data enrichment
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: sensor-table
  - name: config_topic
    inputType: InputTopic
    description: Name of the config topic to listen to.
    defaultValue: config-updates
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: enriched
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
