name: Data encrichment
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: sensor-table
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: transform
  - name: config_topic
    inputType: InputTopic
    multiline: false
    defaultValue: config-updates
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
