name: Data transposition
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: Name of the input topic to listen to.
    defaultValue: sensor-data
  - name: output
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to write to.
    defaultValue: sensor-table
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
